experimental_monorepo_root = true

[monorepo]
config_roots = ["packages/*"]

[tools]
node = "v24.15.0"
pnpm = "10"

[settings]
disable_backends = ["asdf"]
use_versions_host = false
experimental = true
