experimental_monorepo_root = true

[monorepo]
config_roots = ["packages/*"]

[tools]
node = "24.14.1"
pnpm = "10.33.0"
lefthook = "2.1.4"
"github:biomejs/biome" = { version = "2.4.10", version_prefix = "@biomejs/biome@" }
"github:cocogitto/cocogitto" = { version = "7.0.0" }

[tasks.setup]
description = "puts everything in its place"
run = ["mise trust --yes", "mise install", "pnpm install", "lefthook install"]
[tasks.publish]
description = "builds and publishes with changeset"
run = ["mise //...:build", "npx changeset publish --access public"]
[tasks.lint]
description = "attempts to fix what is safe to do"
run = "mise lint-check --write"
[tasks.lint-check]
description = "lint and format check with biome"
run = "biome check --diagnostic-level=warn --no-errors-on-unmatched"
[tasks.typecheck]
description = "checks entire project for type errors"
run = "pnpm tsc"
[tasks.typecheck-staged]
description = "checks passed/staged files for type errors"
run = "pnpm tsc-files"
[tasks.test]
description = "runs all tests"
run = "pnpm vitest"
[tasks.test-staged]
description = "runs tests on passed/staged files"
run = "pnpm vitest related --bail=1 --reporter=github-actions"
[tasks.test-ci]
description = "runs tests silently with quick fail"
run = "pnpm vitest --bail=1 --reporter=github-actions"

[settings]
disable_backends = ["asdf"]
use_versions_host = false
experimental = true
