name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=24"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: |
          yarn typecheck
          yarn biome-check
          yarn test
